meta_product_name: "Repaired"
meta_title: "repaired - Anywhere repair!"
meta_description: "Anywhere repair! "
meta_type: "repairing broken bikes and related things"
meta_url: "https://www.repaired-now.com/"
meta_image: "cover.jpg" # should exist in `app/assets/images/`
